### ISSUE TITLE
Ignore solutions containing shorter solutions

### ISSUE THREAD

**Issue by Eiim** [MrJanHorak/letter-box-solver#1]
For example, today's solutions include `two oceanography`. It's not interesting to me, then, that `act two oceanography` is a possible three-word solution. This would greatly reduce the three-word solution list on some days.

**Comment by MrJanHorak** [comment]
Thank you for pointing that out. I will look into that and see if I can come up with an efficient solution. I agree that is an annoyance. Once again thank you for the suggestion!

**Comment by MrJanHorak** [comment]
@Eiim I am now filtering all already found 2-word solutions from the possible 3-word solutions. Please let me know if this works the way you have envisioned it. And thank you for the input!

**Comment by Eiim** [comment]
Looks great, thanks!
